"""user and inputinfo tables, tabinfo table instead of url table

Revision ID: 32c698df200c
Revises: e6b83b307ea8
Create Date: 2021-02-18 22:07:10.132340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c698df200c'
down_revision = 'e6b83b307ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    op.create_table('input_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_info_cpm'), 'input_info', ['cpm'], unique=False)
    op.create_table('tab_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tab_count', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_info_lang'), 'tab_info', ['lang'], unique=False)
    op.create_index(op.f('ix_tab_info_tab_count'), 'tab_info', ['tab_count'], unique=False)
    op.create_index(op.f('ix_tab_info_timestamp'), 'tab_info', ['timestamp'], unique=False)
    op.drop_table('url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_tab_info_timestamp'), table_name='tab_info')
    op.drop_index(op.f('ix_tab_info_tab_count'), table_name='tab_info')
    op.drop_index(op.f('ix_tab_info_lang'), table_name='tab_info')
    op.drop_table('tab_info')
    op.drop_index(op.f('ix_input_info_cpm'), table_name='input_info')
    op.drop_table('input_info')
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
