"""empty message

Revision ID: 3eeb29e6a0a0
Revises: 497214fbbf17
Create Date: 2021-04-15 19:51:42.662509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3eeb29e6a0a0'
down_revision = '497214fbbf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyboard_timing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keypress', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('keyup', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyboard_timing')
    # ### end Alembic commands ###
