"""added timestamp to input info

Revision ID: 497214fbbf17
Revises: 32c698df200c
Create Date: 2021-02-19 21:57:29.614270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497214fbbf17'
down_revision = '32c698df200c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_info', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_input_info_timestamp'), 'input_info', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_input_info_timestamp'), table_name='input_info')
    op.drop_column('input_info', 'timestamp')
    # ### end Alembic commands ###
